/*
 * Copyright 2013 Gerhard Klostermeier
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


package de.syss.MifareClassicTool;

import android.app.Application;
import android.util.SparseArray;
import de.syss.MifareClassicTool.Activitys.CreateKeyMapActivity;

/**
 * Just a global variables storage class.
 * Yeah I know global variables are ugly...
 * @author Gerhard Klostermeier
 */
public class MCTApp extends Application {

    private SparseArray<byte[][]> mKeyMap;

    /**
     * Get the key map generated by {@link CreateKeyMapActivity}.
     * @return A key map (see {@link MCReader#getKeyMap()}).
     */
    public SparseArray<byte[][]> getKeyMap() {
        return mKeyMap;
    }

    /**
     * Set the key map.
     * @param value A key map (see {@link MCReader#getKeyMap()}).
     */
    public void setKeyMap(SparseArray<byte[][]> value) {
        mKeyMap = value;
    }
}